// app/layout.tsx

import type { Metadata } from "next";
import { Volkhov } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./Components/SmoothScrolling"; // Import SmoothScrolling

const font = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],  // Only include available weights
});

export const metadata: Metadata = {
  title: "Jaado-Travel Agency Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
